object VersionsCore {
    const val gradle = "4.1.0"
    const val kotlin = "1.4.10"
    const val kotlinCoroutines = "1.4.0"
    const val kotlinSerialization = "1.0.0"
    const val retrofit = "2.9.0"
    const val retrofitOkHttp = "4.9.0"
    const val retrofitSerializationConverter = "0.8.0"
    const val dagger = "2.29.1"
    const val rxAndroid = "2.1.1"
    const val rxKotlin = "2.4.0"
    const val rxBinding = "3.0.0"
    const val rxRelay = "2.1.1"
}

object DependenciesCore {
    const val gradlePlugin = "com.android.tools.build:gradle:${VersionsCore.gradle}"
    const val kotlinGradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${VersionsCore.kotlin}"
    const val kotlinSerializationGradlePlugin = "org.jetbrains.kotlin:kotlin-serialization:${VersionsCore.kotlin}"
    const val kotlinCoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${VersionsCore.kotlinCoroutines}"
    const val kotlinSerialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:${VersionsCore.kotlinSerialization}"
    const val retrofitLib = "com.squareup.retrofit2:retrofit:${VersionsCore.retrofit}"
    const val retrofitGsonConverter = "com.squareup.retrofit2:converter-gson:${VersionsCore.retrofit}"
    const val retrofitMoshiConverter = "com.squareup.retrofit2:converter-moshi:${VersionsCore.retrofit}"
    const val retrofitSerializationConverter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:${VersionsCore.retrofitSerializationConverter}"
    const val retrofitRxJava2Adapter = "com.squareup.retrofit2:adapter-rxjava2:${VersionsCore.retrofit}"
    const val retrofitOkHttp = "com.squareup.okhttp3:okhttp:${VersionsCore.retrofitOkHttp}"
    const val retrofitOkHttpLoggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${VersionsCore.retrofitOkHttp}"
    const val dagger = "com.google.dagger:dagger:${VersionsCore.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${VersionsCore.dagger}"
    const val rxAndroid = "io.reactivex.rxjava2:rxandroid:${VersionsCore.rxAndroid}"
    const val rxKotlin = "io.reactivex.rxjava2:rxkotlin:${VersionsCore.rxKotlin}"
    const val rxBinding = "com.jakewharton.rxbinding3:rxbinding:${VersionsCore.rxBinding}"
    const val rxRelay = "com.jakewharton.rxrelay2:rxrelay:${VersionsCore.rxRelay}"
}